TOP=../../../../../..
CURRENT=src/lib/omniORB/omniidl_be/cxx/skel
BASE_OMNI_TREE=../../../../../..

INSTALL=/usr/bin/ginstall -c

include $(TOP)/mk/beforeauto.mk
include ./dir.mk
include $(TOP)/mk/afterauto.mk
