TOP=../../../../..
CURRENT=src/tool/omniidl/python/omniidl
BASE_OMNI_TREE=../../../../..

INSTALL=/usr/bin/ginstall -c

include $(TOP)/mk/beforeauto.mk
include ./dir.mk
include $(TOP)/mk/afterauto.mk
